In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv('airbnb_data.csv',  low_memory= False)

In [5]:
pwd

'C:\\Users\\CHOKO'

In [6]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...,NaN
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/15,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...,NaN
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/15,0.10,3.0,1.0,386.0,NaN,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  object
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  object
 4   host name                       102193 non-null  object
 5   neighbourhood group             102570 non-null  object
 6   neighbourhood                   102583 non-null  object
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  object
 10  country code                    102468 non-null  object
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  object
 13  room type                       102599 non-null  object
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  object
 16  service fee                     102326 non-null  object
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   object
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   object
 25  license                         2 non-null       object
dtypes: float64(9), int64(2), object(15)
memory usage: 20.4+ MB

In [8]:
df.describe()

,id,host id,lat,long,Construction year,minimum nights,number of reviews,reviews per month,review rate number,calculated host listings count,availability 365
count,1.025990e+05,1.025990e+05,102591.000000,102591.000000,102385.000000,102190.000000,102416.000000,86720.000000,102273.000000,102280.000000,102151.000000
mean,2.914623e+07,4.925411e+10,40.728094,-73.949644,2012.487464,8.135845,27.483743,1.374022,3.279106,7.936605,141.133254
std,1.625751e+07,2.853900e+10,0.055857,0.049521,5.765556,30.553781,49.508954,1.746621,1.284657,32.218780,135.435024
min,1.001254e+06,1.236005e+08,40.499790,-74.249840,2003.000000,-1223.000000,0.000000,0.010000,1.000000,1.000000,-10.000000
25%,1.508581e+07,2.458333e+10,40.688740,-73.982580,2007.000000,2.000000,1.000000,0.220000,2.000000,1.000000,3.000000
50%,2.913660e+07,4.911774e+10,40.722290,-73.954440,2012.000000,3.000000,7.000000,0.740000,3.000000,1.000000,96.000000
75%,4.320120e+07,7.399650e+10,40.762760,-73.932350,2017.000000,5.000000,30.000000,2.000000,4.000000,2.000000,269.000000
max,5.736742e+07,9.876313e+10,40.916970,-73.705220,2022.000000,5645.000000,1024.000000,90.000000,5.000000,332.000000,3677.000000

In [9]:
df.sample(5)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
59265,33733396,Sun filled Brooklyn apartment with a view,25294989715,verified,Fer,Brooklyn,Bushwick,40.69686,-73.93325,United States,US,False,strict,Entire home/apt,2015.0,"$1,059",$212,7.0,1.0,1/2/22,0.48,4.0,1.0,308.0,NaN,NaN
30160,17658704,"Convenient, Quiet and Sunny 1 BR Condo in Flus...",68161621761,unconfirmed,Alan,Queens,Flushing,40.76105,-73.82317,United States,US,False,strict,Entire home/apt,2006.0,$520,$104,30.0,4.0,11/9/18,0.31,5.0,15.0,232.0,It is a professional building we ask there be ...,NaN
39553,22846458,Quiet 1 bedroom near Midtown Manhattan,44446417516,unconfirmed,Nicole,Queens,Long Island City,40.73637,-73.93710,United States,US,True,strict,Entire home/apt,2007.0,$915,$183,1.0,0.0,NaN,NaN,3.0,1.0,42.0,- Minimum two night stay - No smoking or drug...,NaN
82524,46579341,Newly renovated 2 bedroom with FREE WIFI,68088117878,unconfirmed,Jonathan,Queens,Flushing,40.76120,-73.82140,United States,US,True,strict,Entire home/apt,2014.0,$581,$116,1.0,104.0,6/28/19,4.44,5.0,1.0,90.0,You have a private room but sounds should be m...,NaN
77628,43875280,Small furnished room in shared West Village apt,1003134054,verified,Sarah,Manhattan,West Village,40.73368,-74.00049,United States,US,False,moderate,Private room,2014.0,$677,$135,2.0,2.0,1/3/17,0.06,4.0,1.0,0.0,NaN,NaN

In [10]:
for categoricals in df.columns:
    print(categoricals)

id
NAME
host id
host_identity_verified
host name
neighbourhood group
neighbourhood
lat
long
country
country code
instant_bookable
cancellation_policy
room type
Construction year
price
service fee
minimum nights
number of reviews
last review
reviews per month
review rate number
calculated host listings count
availability 365
house_rules
license

#Categorical variable

In [11]:

categorical_variable = [categoricals for categoricals in df.columns if df[categoricals].dtypes =='object']
categorical_variable

['NAME',
 'host_identity_verified',
 'host name',
 'neighbourhood group',
 'neighbourhood',
 'country',
 'country code',
 'instant_bookable',
 'cancellation_policy',
 'room type',
 'price',
 'service fee',
 'last review',
 'house_rules',
 'license']

##numerical variable

In [12]:

numerical_variable = [categoricals for categoricals in df.columns if df[categoricals].dtypes !='object']
numerical_variable

['id',
 'host id',
 'lat',
 'long',
 'Construction year',
 'minimum nights',
 'number of reviews',
 'reviews per month',
 'review rate number',
 'calculated host listings count',
 'availability 365']

In [13]:
len(numerical_variable)

11

In [14]:
print('There are {} categorical variables'.format(len(categorical_variable)))

There are 15 categorical variables

## handling missing data

In [15]:
df.head ()

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...,NaN
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...,NaN
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and...",NaN
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.64,4.0,1.0,322.0,NaN,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th...",NaN

In [16]:
df.isnull ().sum()

id                                     0
NAME                                 250
host id                                0
host_identity_verified               289
host name                            406
neighbourhood group                   29
neighbourhood                         16
lat                                    8
long                                   8
country                              532
country code                         131
instant_bookable                     105
cancellation_policy                   76
room type                              0
Construction year                    214
price                                247
service fee                          273
minimum nights                       409
number of reviews                    183
last review                        15893
reviews per month                  15879
review rate number                   326
calculated host listings count       319
availability 365                     448
house_rules                        52131
license                           102597
dtype: int64

In [17]:
df.isnull().sum().sort_values (ascending = False)

license                           102597
house_rules                        52131
last review                        15893
reviews per month                  15879
country                              532
availability 365                     448
minimum nights                       409
host name                            406
review rate number                   326
calculated host listings count       319
host_identity_verified               289
service fee                          273
NAME                                 250
price                                247
Construction year                    214
number of reviews                    183
country code                         131
instant_bookable                     105
cancellation_policy                   76
neighbourhood group                   29
neighbourhood                         16
long                                   8
lat                                    8
id                                     0
host id                                0
room type                              0
dtype: int64

In [18]:
len(df)

102599

In [19]:
(214/102599) * 100

0.20857903098470743

In [20]:
perc_missing = round((df.isnull().sum()/len(df))*100,3).sort_values(ascending = False)
perc_missing

license                           99.998
house_rules                       50.810
last review                       15.490
reviews per month                 15.477
country                            0.519
availability 365                   0.437
minimum nights                     0.399
host name                          0.396
review rate number                 0.318
calculated host listings count     0.311
host_identity_verified             0.282
service fee                        0.266
NAME                               0.244
price                              0.241
Construction year                  0.209
number of reviews                  0.178
country code                       0.128
instant_bookable                   0.102
cancellation_policy                0.074
neighbourhood group                0.028
neighbourhood                      0.016
long                               0.008
lat                                0.008
id                                 0.000
host id                            0.000
room type                          0.000
dtype: float64

In [21]:
perc_missing = round((df.isnull().sum()/len(df))*100,3).sort_values(ascending = False)
pd.DataFrame({'Percentage_Missing':perc_missing})

                                Percentage_Missing
license                                     99.998
house_rules                                 50.810
last review                                 15.490
reviews per month                           15.477
country                                      0.519
availability 365                             0.437
minimum nights                               0.399
host name                                    0.396
review rate number                           0.318
calculated host listings count               0.311
host_identity_verified                       0.282
service fee                                  0.266
NAME                                         0.244
price                                        0.241
Construction year                            0.209
number of reviews                            0.178
country code                                 0.128
instant_bookable                             0.102
cancellation_policy                          0.074
neighbourhood group                          0.028
neighbourhood                                0.016
long                                         0.008
lat                                          0.008
id                                           0.000
host id                                      0.000
room type                                    0.000

In [22]:
df['license'].isnull()

0         True
1         True
2         True
3         True
4         True
          ...
102594    True
102595    True
102596    True
102597    True
102598    True
Name: license, Length: 102599, dtype: bool

In [23]:
df['license'].isnull().sum()

102597

In [24]:
df[df['license'].notnull()]

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules,license
11114,7139598,"Cozy 1 BR on Bedford Avenue, Wburg",73023181304,verified,Christina,Brooklyn,Williamsburg,40.71764,-73.95689,United States,US,True,strict,Private room,2010.0,$702,$140,1.0,1.0,1/3/16,0.02,1.0,1.0,191.0,"Dear Guest, Thank you for appreciating that I ...",41662/AL
72947,41289964,"Cozy 1 BR on Bedford Avenue, Wburg",25804773951,unconfirmed,Christina,Brooklyn,Williamsburg,40.71764,-73.95689,United States,US,True,flexible,Private room,2010.0,$702,$140,1.0,1.0,1/3/16,0.02,1.0,1.0,0.0,NaN,41662/AL

In [25]:
df.drop('license', axis=1)

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/15,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/15,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [26]:
df=df.drop('license', axis=1)

In [27]:
df

,id,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,lat,long,country,country code,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365,house_rules
0,1001254,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.21,4.0,6.0,286.0,Clean up and treat the home the way you'd like...
1,1002102,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.38,4.0,2.0,228.0,Pet friendly but please confirm with me if the...
2,1002403,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0,"I encourage you to use my kitchen, cooking and..."
3,1002755,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.64,4.0,1.0,322.0,NaN
4,1003689,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.10,3.0,1.0,289.0,"Please no smoking in the house, porch or on th..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,6092437,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,40.70862,-73.94651,United States,US,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0,No Smoking No Parties or Events of any kind Pl...
102595,6092990,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,40.80460,-73.96545,United States,US,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/15,0.02,2.0,2.0,395.0,House rules: Guests agree to the following ter...
102596,6093542,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,40.67505,-73.98045,United States,US,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0,NaN
102597,6094094,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,40.74989,-73.93777,United States,US,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/15,0.10,3.0,1.0,386.0,NaN
102598,6094647,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,40.76807,-73.98342,United States,US,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0,NaN

In [28]:
df.drop(['id', 'long', 'lat', 'country code','house_rules'], axis=1, inplace=True)

In [29]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,United States,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.21,4.0,6.0,286.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,United States,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.38,4.0,2.0,228.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,United States,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,United States,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.64,4.0,1.0,322.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,United States,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,United States,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,United States,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/15,0.02,2.0,2.0,395.0
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,United States,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,United States,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/15,0.10,3.0,1.0,386.0
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,United States,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0

In [30]:
df['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'brookln', 'manhatan', 'Queens', nan,
       'Staten Island', 'Bronx'], dtype=object)

In [31]:
df['neighbourhood group']=df['neighbourhood group'].replace('brookln','Brooklyn' )

In [32]:
df['neighbourhood group']=df['neighbourhood group'].replace('manhatan','Manhattan')

In [33]:
df['neighbourhood group'].unique()

array(['Brooklyn', 'Manhattan', 'Queens', nan, 'Staten Island', 'Bronx'],
      dtype=object)

In [34]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,United States,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.21,4.0,6.0,286.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,United States,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.38,4.0,2.0,228.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,United States,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,NaN,NaN,5.0,1.0,352.0
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,United States,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.64,4.0,1.0,322.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,United States,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.10,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,United States,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,NaN,NaN,3.0,1.0,227.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,United States,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/15,0.02,2.0,2.0,395.0
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,United States,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,NaN,NaN,5.0,1.0,342.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,United States,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/15,0.10,3.0,1.0,386.0
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,United States,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,NaN,NaN,3.0,1.0,69.0

In [35]:
df['price'].isnull(),

(0         False
 1         False
 2         False
 3         False
 4         False
           ...
 102594    False
 102595    False
 102596    False
 102597    False
 102598    False
 Name: price, Length: 102599, dtype: bool,)

In [36]:
df['reviews per month'].unique()

array([ 0.21,  0.38,   nan, ...,  7.73, 24.49, 33.08])

In [37]:
round (df['reviews per month'].mean(),3)

1.374

In [38]:
df['reviews per month']=df['reviews per month'].replace('nan', 1.374)

In [39]:
df['reviews per month'].fillna(1.374, inplace=True)

In [40]:
df['reviews per month'].isnull().sum()

0

In [44]:
len(df['last review'].mode().sum())

7

In [42]:
df['last review'].fillna('6/23/19', inplace=True)

In [43]:
df

,NAME,host id,host_identity_verified,host name,neighbourhood group,neighbourhood,country,instant_bookable,cancellation_policy,room type,Construction year,price,service fee,minimum nights,number of reviews,last review,reviews per month,review rate number,calculated host listings count,availability 365
0,Clean & quiet apt home by the park,80014485718,unconfirmed,Madaline,Brooklyn,Kensington,United States,False,strict,Private room,2020.0,$966,$193,10.0,9.0,10/19/21,0.210,4.0,6.0,286.0
1,Skylit Midtown Castle,52335172823,verified,Jenna,Manhattan,Midtown,United States,False,moderate,Entire home/apt,2007.0,$142,$28,30.0,45.0,5/21/22,0.380,4.0,2.0,228.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,NaN,Elise,Manhattan,Harlem,United States,True,flexible,Private room,2005.0,$620,$124,3.0,0.0,6/23/19,1.374,5.0,1.0,352.0
3,NaN,85098326012,unconfirmed,Garry,Brooklyn,Clinton Hill,United States,True,moderate,Entire home/apt,2005.0,$368,$74,30.0,270.0,7/5/19,4.640,4.0,1.0,322.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,verified,Lyndon,Manhattan,East Harlem,United States,False,moderate,Entire home/apt,2009.0,$204,$41,10.0,9.0,11/19/18,0.100,3.0,1.0,289.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102594,Spare room in Williamsburg,12312296767,verified,Krik,Brooklyn,Williamsburg,United States,False,flexible,Private room,2003.0,$844,$169,1.0,0.0,6/23/19,1.374,3.0,1.0,227.0
102595,Best Location near Columbia U,77864383453,unconfirmed,Mifan,Manhattan,Morningside Heights,United States,True,moderate,Private room,2016.0,$837,$167,1.0,1.0,7/6/15,0.020,2.0,2.0,395.0
102596,"Comfy, bright room in Brooklyn",69050334417,unconfirmed,Megan,Brooklyn,Park Slope,United States,True,moderate,Private room,2009.0,$988,$198,3.0,0.0,6/23/19,1.374,5.0,1.0,342.0
102597,Big Studio-One Stop from Midtown,11160591270,unconfirmed,Christopher,Queens,Long Island City,United States,True,strict,Entire home/apt,2015.0,$546,$109,2.0,5.0,10/11/15,0.100,3.0,1.0,386.0
102598,585 sf Luxury Studio,68170633372,unconfirmed,Rebecca,Manhattan,Upper West Side,United States,False,flexible,Entire home/apt,2010.0,"$1,032",$206,1.0,0.0,6/23/19,1.374,3.0,1.0,69.0

In [49]:
df['review rate number'].unique()

array([ 4.,  5.,  3., nan,  2.,  1.])

In [52]:
df['review rate number'].fillna(5.0, inplace=True)

In [53]:
df['review rate number']

0         4.0
1         4.0
2         5.0
3         4.0
4         3.0
         ...
102594    3.0
102595    2.0
102596    5.0
102597    3.0
102598    3.0
Name: review rate number, Length: 102599, dtype: float64

In [54]:
df['review rate number'].unique()

array([4., 5., 3., 2., 1.])